### ISSUE TITLE
Hangouts Video

### ISSUE THREAD

**Issue by ghost** [ludios/mute-new-tabs#6]
Video calls are muted.
Unable to find the mute/unmute icon.
Phone calls are OK (not muted)

Google Hangouts 2017.110.418.2 plugin for Google Chrome 56.0.2924.87
OS Win 8.1

**Comment by ivan** [comment]
Thanks for the report.  I will have to look into this and prevent Mute New Tabs from touching Hangouts.  Can you confirm that video calls work fine with the Mute New Tabs extension disabled? (Chrome will need a restart if the windows are already muted)

**Comment by ghost** [comment]
Yes, when Mute New Tabs extension is disabled, then Hangouts video works fine.

Note: Hangouts phone call works also with Mute New Tabs extension enabled.

**Comment by ivan** [comment]
Reopening until a new version is released very soon

**Comment by ghost** [comment]
Meanwhile (untile a new version is released) I've overwritten mute_tabs.js with the new one you provided and, after restart, the sound works for Goggle Hangouts Videocall.
Thanks!

**Comment by ivan** [comment]
Thanks again for reporting this really bad bug.  It should be fixed in the 1.0.0 release [in the Chrome Web Store](https://chrome.google.com/webstore/detail/mute-new-tabs/inggmeoccpodpdhmejgmgagmmcdgdkih).

You can force an update at chrome://extensions -> check Developer Mode -> Update Extensions Now.

Let me know if you find any other issues!
